version: '3.8'

services:
  web:
    build: .
    image: ctw1985/food-chatbot:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env